### ISSUE TITLE
test_lockhammer.py : ImportError: No module named sh

### ISSUE THREAD

**Issue by zhangfeigao** [ARM-software/synchronization-benchmarks#44]
python3 test_lockhammer.py 
Traceback (most recent call last):
  File "test_lockhammer.py", line 38, in <module>
    import sh
ImportError: No module named 'sh'

python2 test_lockhammer.py 
Traceback (most recent call last):
  File "test_lockhammer.py", line 38, in <module>
    import sh
ImportError: No module named sh

**Comment by Amar-Bharamshetti** [comment]
Observing same issue. Please let us know if there is any way to fix it

**Comment by el8** [comment]
Manually installing python3-sh solved the issue for me.

Please document the required packages in README.rst of benchmarks/lockhammer under "Build & Run".
